# typed: false
# frozen_string_literal: true

require "json"
require "etc"

# Generated by eng/release/generate-package-manifests.cs. Do not edit by hand.
class HpdosBeta < Formula
  env :std

  desc "Interactive HPD-OS coding TUI powered by HPD-Agent"
  homepage "https://github.com/HPD-AI/HPD-OS"
  version "0.1.0-beta.1"
  url "https://github.com/HPD-AI/homebrew-tap", using: :git, branch: "main"

  depends_on "gh" => :run

  def release_tag
    "hpdos-tui-v#{version}"
  end

  def artifact_name
    if OS.mac?
      Hardware::CPU.arm? ? "hpdos-osx-arm64.tar.gz" : "hpdos-osx-x64.tar.gz"
    elsif OS.linux?
      Hardware::CPU.arm? ? "hpdos-linux-arm64.tar.gz" : "hpdos-linux-x64.tar.gz"
    else
      odie "Unsupported platform for HPDOS release binary."
    end
  end

  def current_user_home
    candidates = [
      ENV["HOME"],
      Etc.getpwuid(Process.uid)&.dir,
      ENV["SUDO_USER"] && "/Users/#{ENV["SUDO_USER"]}",
      ENV["USER"] && "/Users/#{ENV["USER"]}",
      ENV["LOGNAME"] && "/Users/#{ENV["LOGNAME"]}",
      ENV["USER"] && "/home/#{ENV["USER"]}",
      begin
        login = Etc.getlogin
        ["/Users/#{login}", "/home/#{login}"] if login && !login.empty?
      rescue StandardError
        nil
      end,
      "/tmp",
    ].compact.flatten.uniq

    candidates.find { |path| path.is_a?(String) && !path.empty? && File.directory?(path) }
  end

  def github_token
    token = ENV["HOMEBREW_GITHUB_API_TOKEN"] || ENV["GITHUB_TOKEN"] || ENV["GH_TOKEN"]
    token = token.to_s.strip
    return token unless token.empty?
    return "" unless which("gh")

    candidate_home = current_user_home
    env = candidate_home ? { "HOME" => candidate_home } : {}
    token = Utils.safe_popen_read(env, "gh", "auth", "token", "-h", "github.com").strip
    token
  rescue ErrorDuringExecution
    ""
  end

  def release_metadata(token)
    release_url = "https://api.github.com/repos/HPD-AI/HPD-OS/releases/tags/#{release_tag}"
    headers = [
      "--header", "Accept: application/vnd.github+json",
      "--header", "X-GitHub-Api-Version: 2022-11-28",
    ]
    unless token.empty?
      headers << "--header"
      headers << "Authorization: Bearer #{token}"
    end

    Utils.safe_popen_read("curl", "--fail", "--silent", *headers, release_url)
  end

  def download_asset(token, browser_download_url)
    headers = ["--header", "Accept: application/octet-stream"]
    unless token.empty?
      headers << "--header"
      headers << "Authorization: Bearer #{token}"
    end

    system(
      "curl",
      "--fail",
      "--location",
      "--output",
      artifact_name,
      *headers,
      browser_download_url,
    )
  end

  def install
    token = github_token
    if token.empty?
      odie <<~MSG
        A GitHub token is required to install #{name}. Set one of:
        HOMEBREW_GITHUB_API_TOKEN, GH_TOKEN, or GITHUB_TOKEN, then retry.
      MSG
    end

    release_json = begin
      release_metadata(token)
    rescue ErrorDuringExecution
      begin
        release_metadata("")
      rescue ErrorDuringExecution
        odie <<~MSG
          Failed to read release #{release_tag} from GitHub. If this repo is private,
          set one of HOMEBREW_GITHUB_API_TOKEN, GH_TOKEN, or GITHUB_TOKEN, then retry.
        MSG
      end
    end

    release = begin
      JSON.parse(release_json)
    rescue JSON::ParserError
      odie "Failed to parse GitHub release response for #{release_tag}. Verify token scope."
    end

    artifact = release.fetch("assets", []).find { |a| a["name"] == artifact_name }
    odie "Release asset #{artifact_name} not found in #{release_tag}." if artifact.nil?
    download_url = artifact.fetch("url", "")
    download_url = artifact["browser_download_url"] if download_url.empty?

    downloaded = download_asset(token, download_url)
    downloaded = download_asset("", download_url) if !downloaded && !token.empty?
    odie "Failed to download #{artifact_name}" unless downloaded && File.exist?(artifact_name)

    system "tar", "-xzf", artifact_name
    odie "Downloaded archive did not contain expected hpdos binary." unless File.exist?("hpdos")

    bin.install "hpdos"
    bin.install_symlink bin/"hpdos" => "hpdos-beta"
  end

  test do
    assert_match "HPDOS", shell_output("#{bin}/hpdos --help")
  end
end
