# typed: false
# frozen_string_literal: true

require "json"

# Generated by eng/release/generate-package-manifests.cs. Do not edit by hand.
class HpdosBeta < Formula
  desc "Interactive HPD-OS coding TUI powered by HPD-Agent"
  homepage "https://github.com/HPD-AI/HPD-OS"
  version "0.1.0-beta.1"
  url "https://github.com/HPD-AI/homebrew-tap", using: :git, branch: "main"

  depends_on "gh" => :run

  def release_tag
    "hpdos-tui-v#{version}"
  end

  def artifact_name
    if OS.mac?
      Hardware::CPU.arm? ? "hpdos-osx-arm64.tar.gz" : "hpdos-osx-x64.tar.gz"
    elsif OS.linux?
      Hardware::CPU.arm? ? "hpdos-linux-arm64.tar.gz" : "hpdos-linux-x64.tar.gz"
    else
      odie "Unsupported platform for HPDOS release binary."
    end
  end

  def gh_executable
    Formula["gh"].opt_bin.join("gh").to_s
  end

  def gh_token
    token = ENV["HOMEBREW_GITHUB_API_TOKEN"] || ENV["GITHUB_TOKEN"] || ENV["GH_TOKEN"]
    return token.to_s.strip unless token.to_s.strip.empty?

    token = Utils.safe_popen_read(gh_executable, "auth", "token", "-h", "github.com").strip
    token.empty? ? "" : token
  rescue ErrorDuringExecution
    ""
  end

  def github_headers
    token = gh_token
    headers = [
      "--header", "Accept: application/vnd.github+json",
      "--header", "X-GitHub-Api-Version: 2022-11-28",
    ]
    headers << "--header" << "Authorization: token #{token}" unless token.empty?
    headers
  end

  def download_via_gh
    return false if gh_executable.empty?

    system(
      gh_executable,
      "release",
      "download",
      release_tag,
      "--repo",
      "HPD-AI/HPD-OS",
      "--pattern",
      artifact_name,
      "--output",
      artifact_name,
      "--clobber",
    )
  end

  def download_via_api
    release_url = "https://api.github.com/repos/HPD-AI/HPD-OS/releases/tags/#{release_tag}"
    release = JSON.parse(Utils.safe_popen_read("curl", "--fail", "--silent", "--show-error", "--location", *github_headers, release_url))

    asset = Array(release["assets"]).find { |a| a["name"] == artifact_name }
    odie "Release asset #{artifact_name} was not found in #{release_tag}." unless asset

    output = Utils.safe_popen_read(
      "curl",
      "--fail",
      "--location",
      "--silent",
      "--show-error",
      "--output",
      artifact_name,
      "--header",
      "Accept: application/octet-stream",
      *github_headers,
      asset["url"],
    )
    output.empty?
  end

  def install
    downloaded = download_via_gh

    if !downloaded || !File.exist?(artifact_name)
      begin
        download_via_api
      rescue StandardError
        # fall through so we can surface a clear, actionable error
      end
    end

    odie <<~MSG unless File.exist?(artifact_name)
      Failed to download #{artifact_name} from release #{release_tag}.
      If this repository is private, ensure the GitHub CLI is logged in:
        gh auth login
      Then retry:
        brew install hpdos-beta
    MSG

    if artifact_name.end_with?(".tar.gz")
      system "tar", "-xzf", artifact_name
    elsif artifact_name.end_with?(".zip")
      system "unzip", "-q", artifact_name
    else
      odie "Unsupported archive format for #{artifact_name}."
    end

    binary = Dir["**/hpdos", "**/hpdos.exe"].find { |path| File.file?(path) && File.executable?(path) }
    odie "Downloaded archive did not contain an executable binary." unless binary

    bin.install binary
  end

  test do
    assert_match "HPDOS", shell_output("#{bin}/hpdos --help")
  end
end
