# typed: false
# frozen_string_literal: true

require "json"

# Generated by eng/release/generate-package-manifests.cs. Do not edit by hand.
class HpdosBeta < Formula
  env :std

  desc "Interactive HPD-OS coding TUI powered by HPD-Agent"
  homepage "https://github.com/HPD-AI/HPD-OS"
  version "0.1.0-beta.1"
  url "https://github.com/HPD-AI/homebrew-tap", using: :git, branch: "main"

  depends_on "gh" => :run

  def release_tag
    "hpdos-tui-v#{version}"
  end

  def artifact_name
    if OS.mac?
      Hardware::CPU.arm? ? "hpdos-osx-arm64.tar.gz" : "hpdos-osx-x64.tar.gz"
    elsif OS.linux?
      Hardware::CPU.arm? ? "hpdos-linux-arm64.tar.gz" : "hpdos-linux-x64.tar.gz"
    else
      odie "Unsupported platform for HPDOS release binary."
    end
  end

  def install
    token = ENV["HOMEBREW_GITHUB_API_TOKEN"] || ENV["GITHUB_TOKEN"] || ENV["GH_TOKEN"]
    token = token.to_s.strip
    if token.empty?
      # Optional fallback: use gh CLI config if available
      if which("gh")
        token = begin
          Utils.safe_popen_read("gh", "auth", "token", "-h", "github.com").strip
        rescue ErrorDuringExecution
          ""
        end
      end
    end
    token = token.to_s.strip

    if token.empty?
      odie <<~MSG
        HPDOS release artifacts are in a private GitHub repo.
        Set one of HOMEBREW_GITHUB_API_TOKEN, GH_TOKEN, or GITHUB_TOKEN before installing.
      MSG
    end

    auth_header = "Authorization: Bearer #{token}"
    release_url = "https://api.github.com/repos/HPD-AI/HPD-OS/releases/tags/#{release_tag}"
    release_json = Utils.safe_popen_read(
      "curl", "--fail", "--silent",
      "--header", "Accept: application/vnd.github+json",
      "--header", auth_header,
      release_url
    )
    release = JSON.parse(release_json)
    artifact = release.fetch("assets", []).find { |a| a["name"] == artifact_name }
    odie "Release asset #{artifact_name} not found in #{release_tag}." if artifact.nil?

    system(
      "curl", "--fail", "--location", "--output", artifact_name,
      "--header", "Accept: application/octet-stream",
      "--header", auth_header,
      artifact["browser_download_url"],
    )

    system "tar", "-xzf", artifact_name
    bin.install "hpdos"
    bin.install_symlink bin/"hpdos" => "hpdos-beta"
  end

  test do
    assert_match "HPDOS", shell_output("#{bin}/hpdos --help")
  end
end
